const initialCategories = [
  { type: 'language', name: 'English' },
  { type: 'language', name: 'Urdu' },
  { type: 'subcategory', name: 'Story' },
  { type: 'subcategory', name: 'Self-help' },
  { type: 'subcategory', name: 'Islamic' },
  { type: 'subcategory', name: 'Educational' },
  { type: 'subcategory', name: 'Nature' },
  { type: 'subcategory', name: 'Health' }
];

const initialBooks = [
  { title: 'The Magic Key', language: 'English', subcategory: 'Story', author: 'Oxford Reading Tree' },
  { title: 'Castle Adventure', language: 'English', subcategory: 'Story', author: '' },
  { title: 'The Giant', language: 'English', subcategory: 'Story', author: '' },
  { title: 'Robin Hood', language: 'English', subcategory: 'Story', author: '' },
  { title: 'The Treasure Chest', language: 'English', subcategory: 'Story', author: '' },
  { title: 'The Kidnappers', language: 'English', subcategory: 'Story', author: '' },
  { title: 'Land of the Dinosaurs', language: 'English', subcategory: 'Story', author: '' },
  { title: 'Village in the Snow', language: 'English', subcategory: 'Story', author: '' },
  { title: 'Kipper and the Giant', language: 'English', subcategory: 'Story', author: '' },
  { title: 'Muhammad (SAW) Momentous Martyrdom', language: 'English', subcategory: 'Islamic', author: 'Muhammad Z. Awan' },
  { title: "Edward de Bono's Textbook of Wisdom", language: 'English', subcategory: 'Self-help', author: 'Edward de Bono' },
  { title: 'Influence: The Psychology of Persuasion', language: 'English', subcategory: 'Self-help', author: 'Robert B. Cialdini' },
  { title: 'The Power of Habit', language: 'English', subcategory: 'Self-help', author: 'Charles Duhigg' },
  { title: 'The 7 Habits of Highly Effective People', language: 'English', subcategory: 'Self-help', author: 'Stephen R. Covey' },
  { title: 'جلیبیاں', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'چالاک کون؟', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'شاہ موش', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'بونے اور چڑیا کا بچہ', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'جیومیٹری بوکس', language: 'Urdu', subcategory: 'Educational', author: '' },
  { title: 'اُلٹے میاں', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'غبارے', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'کشمش', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'گائے جو نہر میں گر گئی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'خوش بو', language: 'Urdu', subcategory: 'Nature', author: '' },
  { title: 'بلی شیر کی خالہ', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'پرندے', language: 'Urdu', subcategory: 'Nature', author: '' },
  { title: 'شرارت بھرے تھے', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'آ آچھیں۔۔۔', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'اچھی یادیں', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'الوداعی تقریب', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'نئی دوستی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'احمق کون', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'نیا کھلاڑی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'دانت کا درد', language: 'Urdu', subcategory: 'Health', author: '' },
  { title: 'دو بھائی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'اسد کا پینسل بکس', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'ہم ہیں سمندر کے باسی', language: 'Urdu', subcategory: 'Nature', author: '' },
  { title: 'نئے پڑوسی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'بیمار کا حال', language: 'Urdu', subcategory: 'Health', author: '' },
  { title: 'گل دان کس نے توڑا', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'پرہیز', language: 'Urdu', subcategory: 'Health', author: '' },
  { title: 'اور جنگل بچ گیا', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'بندر اور خوبانیاں', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'کھیت سے ہانڈی تک', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'اعضاء کی لڑائی', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'جامن', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'گرمی', language: 'Urdu', subcategory: 'Nature', author: '' },
  { title: 'صنعتی میلہ', language: 'Urdu', subcategory: 'Educational', author: '' },
  { title: 'بطخ اور بطخے میاں', language: 'Urdu', subcategory: 'Story', author: '' },
  { title: 'پہاڑوں کی فریاد', language: 'Urdu', subcategory: 'Story', author: 'خالد حسینی' },
  { title: 'حیاتِ صحابیات کے درخشاں پہلو', language: 'Urdu', subcategory: 'Islamic', author: '' }
];

module.exports = {
  initialCategories,
  initialBooks
};